FROM ghcr.io/rapidfort/kimia-bud:1.0.26@sha256:265d57cd232d47dd4ee3e2e6dfaa3836d6cce9f0bc9fe79a0ecdea60577fff37

ARG PLUGIN_VERSION=dev
ARG PLUGIN_REVISION=unknown
ARG PLUGIN_CREATED=

ENV KIMIA_VERSION=1.0.26 \
    TMPDIR=/dev/shm

LABEL org.opencontainers.image.title="drone-kimia-gar" \
      org.opencontainers.image.description="Harness/Drone adapter for RapidFort Kimia using Google Artifact Registry authentication" \
      org.opencontainers.image.source="https://github.com/harness-community/drone-kimia" \
      org.opencontainers.image.url="https://github.com/harness-community/drone-kimia" \
      org.opencontainers.image.documentation="https://github.com/harness-community/drone-kimia#readme" \
      org.opencontainers.image.vendor="Harness Community" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="${PLUGIN_VERSION}" \
      org.opencontainers.image.revision="${PLUGIN_REVISION}" \
      org.opencontainers.image.created="${PLUGIN_CREATED}" \
      org.opencontainers.image.base.name="ghcr.io/rapidfort/kimia-bud:1.0.26" \
      org.opencontainers.image.base.digest="sha256:265d57cd232d47dd4ee3e2e6dfaa3836d6cce9f0bc9fe79a0ecdea60577fff37"

COPY release/linux/arm64/kimia-gar /usr/local/bin/kimia-gar

USER 0:0
RUN mkdir -p /kaniko \
    && chmod 0755 /kaniko \
    && ln -s /usr/local/bin/kimia-gar /kaniko/kaniko-gar
USER 1000:1000

RUN test "$(id -u):$(id -g)" = "1000:1000" \
    && test "${HOME}" = "/home/kimia" \
    && test "${TMPDIR}" = "/dev/shm" \
    && test -d "${TMPDIR}" \
    && test -w "${TMPDIR}" \
    && test "$(pwd)" = "/home/kimia" \
    && test "$(readlink /kaniko/kaniko-gar)" = "/usr/local/bin/kimia-gar" \
    && test ! -w /kaniko \
    && /usr/local/bin/kimia-gar --version \
    && /kaniko/kaniko-gar --version \
    && /usr/local/bin/kimia-gar --help | grep -q "PLUGIN_EXPAND_TAG" \
    && /usr/local/bin/kimia-gar --help | grep -q "PLUGIN_PUSH_ONLY" \
    && /usr/local/bin/kimia-gar --help | grep -q "PLUGIN_DAEMON_OFF" \
    && /usr/local/bin/kimia-gar --help | grep -q "PLUGIN_JSON_KEY" \
    && buildah --version | grep -q "1.44.0" \
    && grep -Eq '^[[:space:]]*driver[[:space:]]*=[[:space:]]*"vfs"[[:space:]]*$' /home/kimia/.config/containers/storage.conf \
    && test -u /usr/bin/newuidmap \
    && test -u /usr/bin/newgidmap \
    && grep -qx 'kimia:100000:65536' /etc/subuid \
    && grep -qx 'kimia:100000:65536' /etc/subgid

ENTRYPOINT ["/usr/local/bin/kimia-gar"]
CMD []
