FROM ghcr.io/rapidfort/kimia:1.0.26@sha256:e074b68d90f2770e0540c5610ca4335e985772cb36ef61d90109978fdc626cf9

ARG PLUGIN_VERSION=dev
ARG PLUGIN_REVISION=unknown
ARG PLUGIN_CREATED=

ENV KIMIA_VERSION=1.0.26

LABEL org.opencontainers.image.title="drone-kimia" \
      org.opencontainers.image.description="Harness/Drone adapter for RapidFort Kimia using Docker-compatible registry authentication" \
      org.opencontainers.image.source="https://github.com/harness-community/drone-kimia" \
      org.opencontainers.image.url="https://github.com/harness-community/drone-kimia" \
      org.opencontainers.image.documentation="https://github.com/harness-community/drone-kimia#readme" \
      org.opencontainers.image.vendor="Harness Community" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="${PLUGIN_VERSION}" \
      org.opencontainers.image.revision="${PLUGIN_REVISION}" \
      org.opencontainers.image.created="${PLUGIN_CREATED}" \
      org.opencontainers.image.base.name="ghcr.io/rapidfort/kimia:1.0.26" \
      org.opencontainers.image.base.digest="sha256:e074b68d90f2770e0540c5610ca4335e985772cb36ef61d90109978fdc626cf9"

COPY release/linux/arm64/kimia-docker /usr/local/bin/kimia-docker

USER 0:0
RUN mkdir -p /kaniko \
    && chmod 0755 /kaniko \
    && ln -s /usr/local/bin/kimia-docker /kaniko/kaniko-docker
USER 1000:1000

RUN test "$(id -u):$(id -g)" = "1000:1000" \
    && test "${HOME}" = "/home/kimia" \
    && test "$(pwd)" = "/home/kimia" \
    && test "$(readlink /kaniko/kaniko-docker)" = "/usr/local/bin/kimia-docker" \
    && test ! -w /kaniko \
    && /usr/local/bin/kimia-docker --version \
    && /kaniko/kaniko-docker --version \
    && /usr/local/bin/kimia-docker --help | grep -q "PLUGIN_EXPAND_TAG" \
    && /usr/local/bin/kimia-docker --help | grep -q "PLUGIN_PUSH_ONLY" \
    && /usr/local/bin/kimia-docker --help | grep -q "PLUGIN_DAEMON_OFF" \
    && /usr/local/bin/kimia-docker --help | grep -q "PLUGIN_USERNAME" \
    && buildkitd --version \
    && rootlesskit --version

ENTRYPOINT ["/usr/local/bin/kimia-docker"]
CMD []
