FROM ghcr.io/rapidfort/kimia-bud:1.0.26@sha256:265d57cd232d47dd4ee3e2e6dfaa3836d6cce9f0bc9fe79a0ecdea60577fff37

ARG PLUGIN_VERSION=dev
ARG PLUGIN_REVISION=unknown
ARG PLUGIN_CREATED=

ENV KIMIA_VERSION=1.0.26 \
    CONTAINERS_STORAGE_CONF=/home/kimia/.config/containers/storage.conf \
    NETAVARK_LOCK_PATH=/tmp/lock/netavark.lock \
    TMPDIR=/dev/shm \
    XDG_RUNTIME_DIR=/tmp/run

LABEL org.opencontainers.image.title="drone-kimia-ecr" \
      org.opencontainers.image.description="Harness/Drone adapter for RapidFort Kimia using Amazon Elastic Container Registry authentication" \
      org.opencontainers.image.source="https://github.com/harness-community/drone-kimia" \
      org.opencontainers.image.url="https://github.com/harness-community/drone-kimia" \
      org.opencontainers.image.documentation="https://github.com/harness-community/drone-kimia#readme" \
      org.opencontainers.image.vendor="Harness Community" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="${PLUGIN_VERSION}" \
      org.opencontainers.image.revision="${PLUGIN_REVISION}" \
      org.opencontainers.image.created="${PLUGIN_CREATED}" \
      org.opencontainers.image.base.name="ghcr.io/rapidfort/kimia-bud:1.0.26" \
      org.opencontainers.image.base.digest="sha256:265d57cd232d47dd4ee3e2e6dfaa3836d6cce9f0bc9fe79a0ecdea60577fff37"

COPY release/linux/arm64/kimia-ecr /usr/local/bin/kimia-ecr

USER 0:0
RUN mkdir -p /kaniko "${XDG_RUNTIME_DIR}" "${NETAVARK_LOCK_PATH%/*}" \
    && chown -R 0:0 /home/kimia "${XDG_RUNTIME_DIR}" "${NETAVARK_LOCK_PATH%/*}" \
    && chmod 0700 "${XDG_RUNTIME_DIR}" "${NETAVARK_LOCK_PATH%/*}" \
    && chmod 0755 /kaniko \
    && ln -s /usr/local/bin/kimia-ecr /kaniko/kaniko-ecr

RUN test "$(id -u):$(id -g)" = "0:0" \
    && test "${HOME}" = "/home/kimia" \
    && test "$(stat -c '%u:%g' "${HOME}")" = "0:0" \
    && test -w "${HOME}" \
    && test "${TMPDIR}" = "/dev/shm" \
    && test -d "${TMPDIR}" \
    && test -w "${TMPDIR}" \
    && test "${XDG_RUNTIME_DIR}" = "/tmp/run" \
    && test "$(stat -c '%u:%g:%a' "${XDG_RUNTIME_DIR}")" = "0:0:700" \
    && test "${NETAVARK_LOCK_PATH}" = "/tmp/lock/netavark.lock" \
    && test "$(stat -c '%u:%g:%a' "${NETAVARK_LOCK_PATH%/*}")" = "0:0:700" \
    && test "$(pwd)" = "/home/kimia" \
    && test -w "$(pwd)" \
    && test "$(readlink /kaniko/kaniko-ecr)" = "/usr/local/bin/kimia-ecr" \
    && test "$(stat -c '%u:%g:%a' /kaniko)" = "0:0:755" \
    && /usr/local/bin/kimia-ecr --version \
    && /kaniko/kaniko-ecr --version \
    && /usr/local/bin/kimia-ecr --help | grep -q "PLUGIN_EXPAND_TAG" \
    && /usr/local/bin/kimia-ecr --help | grep -q "PLUGIN_PUSH_ONLY" \
    && /usr/local/bin/kimia-ecr --help | grep -q "PLUGIN_DAEMON_OFF" \
    && /usr/local/bin/kimia-ecr --help | grep -q "PLUGIN_ACCESS_KEY" \
    && buildah --version | grep -q "1.44.0" \
    && grep -Eq '^[[:space:]]*driver[[:space:]]*=[[:space:]]*"vfs"[[:space:]]*$' "${CONTAINERS_STORAGE_CONF}" \
    && test -u /usr/bin/newuidmap \
    && test -u /usr/bin/newgidmap \
    && grep -qx 'kimia:100000:65536' /etc/subuid \
    && grep -qx 'kimia:100000:65536' /etc/subgid

ENTRYPOINT ["/usr/local/bin/kimia-ecr"]
CMD []
